[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.6.0",
    "matplotlib>=3.10.7",
    "pygame>=2.6.1",
    "tinygrad>=0.11.0",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
]
